### PR TITLE
Flush pipeline when PMP CSRs are cleared

### PR DESCRIPTION
**Pull request by marnovandermaas**
Closes: https://github.com/lowRISC/ibex/issues/2193

### CODE REVIEW

**Review by nbdd0121 — APPROVED** [review]

**Comment by mndstrmr** [comment]
This is my suggested solution, but I think it's wrong: Doesn't this prevent the `else` case ever being entered? Indeed was the `else` case ever correct? It would previously not be entered e.g. on a `WRITE` to a debug register, which it clearly should be.

I think the `if` and `else` should be merged, and the inner `if` statements merged into their parents, something like the below:

```sv
assign csr_pipe_flush = 
    csr_op_en_o == 1'b1 && csr_op_o != CSR_OP_READ && (
    	csr_num_e'(instr_rdata_i[31:20]) == CSR_MSTATUS   ||
     	csr_num_e'(instr_rdata_i[31:20]) == CSR_MIE       ||
      	csr_num_e'(instr_rdata_i[31:20]) == CSR_MSECCFG   ||
      	// To catch all PMPCFG/PMPADDR registers, get the shared top most 7 bits.
      	instr_rdata_i[31:25] == 7'h1D 		  	  ||
    	csr_num_e'(instr_rdata_i[31:20]) == CSR_DCSR      ||
	csr_num_e'(instr_rdata_i[31:20]) == CSR_DPC       ||
	csr_num_e'(instr_rdata_i[31:20]) == CSR_DSCRATCH0 ||
	csr_num_e'(instr_rdata_i[31:20]) == CSR_DSCRATCH1
    );
```

**Review by GregAC — CHANGES_REQUESTED** [review]
I wanted to discuss different ways to approach this so please do not merge this for now.

**Comment by GregAC** [comment]
I also don't want to make any RTL changes to Ibex until I've sorted the OT earlgrey release branch

**Comment by marnovandermaas** [comment]
Closing this PR because it probably needs a different solution.

**Pull request closed without merging**
