### PR TITLE
Block diagram update

### PR DESCRIPTION
**Pull request by marnovandermaas**
My hackday project, which I think improves the block diagram formatting without doing any major re-organization.

### CODE REVIEW

**Review by elliotb-lowrisc — CHANGES_REQUESTED** [review]
This looks nice in Inkscape on my local computer, but has problems when rendered on GitHub: https://github.com/lowRISC/ibex/tree/c06a6b5c2efa093e0e5a686e3c208b7a6b37cebf

Note the loss of white background behind the "Instruction Memory Interface" box, the "Instruction Fetch" text is not shown as Exo 2 and is overrunning the edge of its containing box, and the tiny text below the Prefetch Buffer is not rendered at all.

**Review by elliotb-lowrisc — CHANGES_REQUESTED** [review]
Ah, the CSS approach I suggested for the font doesn't seem to work on GitHub after all.

**Comment by marnovandermaas** [comment]
Ok, I've done the boring thing and moved back to liberation sans.

**Review by elliotb-lowrisc — CHANGES_REQUESTED** [review]
1. debug_req_i is unreadable on a dark background (e.g. dark-mode GitHub). Suggest increasing size back to what it was and adding either a white outline or background shape.
2. Text below Prefetch Buffer not rendering on GitHub. Suggest looking for layer issues.

Nits:
1. I liked the `sans-serif` "Ibex Core" title better.
2. "PMP Check" text is rather large (in both places).

**Review by elliotb-lowrisc — APPROVED** [review]
Looking good

**Review by hcallahan-lowrisc — APPROVED** [review]

**Pull request merged**
