### PR TITLE
[doc/um] Updated the python requirements run command for sw simple sy…

### PR DESCRIPTION
**Pull request by rahulraveendran15-coder**
…stem

Updated the README file for python requirements run command.
@imphil 
Signed-off-by: Rahul Raveendran <rahul.raveendran@acconeer.com>

### CODE REVIEW

**Comment by imphil** [comment]
Nice one! This looks great! I'll merge this as soon as the checks pass.

One small detail for your next pull request: keep the first line of the commit message preferably under 50 characters, since it is used as "summary". If you have more text, you can write a longer description below that, e.g. like that:

```
[doc/um] Fix documentation on Python requirements

Fix the command to install Python dependencies in the simple system.

Signed-off-by: Rahul Raveendran <rahul.raveendran@acconeer.com>
```

This also helps GitHub to show the summary better, i.e. ensure that there's no "..." visible at 
grafik


(No need to change anything for this PR, however.)

**Review by imphil — APPROVED** [review]

**Comment by imphil** [comment]
Congratulations to getting your first-ever pull request merged, and your first code contribution to Ibex!

**Comment by rahulraveendran15-coder** [comment]
Thank you very much Imphil, I will keep these notes for my next pull request.
One doubt I have is that how can I add reviewers to my pull request, I added your name using @ in the description is there any other way to add ?

**Comment by imphil** [comment]
You can select reviewers on the top-right on the PR page (i.e. here). But don't worry about it, we'll see your PR and look at it even without it.

**Comment by rahulraveendran15-coder** [comment]
All right, but if you see in the image the reviewers is kind of disabled for me to add. Thats why.
image

**Comment by rswarbrick** [comment]
Yep, I think adding reviewers through the interface like that needs some extra permissions. I'm not sure whether we can turn that off. Otherwise, the lowRISC hardware engineers monitor these issues and PRs, so we can always point them at reviewers as needed.

**Comment by rahulraveendran15-coder** [comment]
Okay, fine thank you

**Pull request merged**
