### PR TITLE
Delay simulator finish

### PR DESCRIPTION
**Pull request by towoe**
The tracer needs time to log the final instruction.
Introduce a counter to delay calling the simulation finish.

@imphil is that what you had in mind?

### CODE REVIEW

**Comment by imphil** [comment]
And I assume you tested this and it fixes the problem you reported in #468?

**Comment by towoe** [comment]
> LGTM, but it looks lint-suspicious. Can you double-check Verilator lint on the type widths?

Thought it might be good to be able to easily increase the delay.

Never did the lint check :) Is `fusesoc --cores-root . run --target=lint lowrisc:ibex:ibex_core_tracing` supposed to do the trick? Fails for me, but with warning from another part.

**Comment by towoe** [comment]
> And I assume you tested this and it fixes the problem you reported in #468?

Yes
```
% tail -n 4 trace_core_00000000.log
           1262        627      001002b8        000202b7        lui     x5,0x20   x5=0x00020000
           1264        628      001002bc        00428293        addi    x5,x5,4   x5:0x00020000  x5=0x00020004
           1266        629      001002c0        4305    c.li    x6,1      x6=0x00000001
           1270        631      001002c2        0062a023        sw      x6,0(x5)          x5:0x00020004  x6:0x00000001 PA:0x00020004 store:0x00000001 load:0x00000000
```

**Comment by imphil** [comment]
> Is fusesoc --cores-root . run --target=lint lowrisc:ibex:ibex_core_tracing supposed to do the trick?

That will only lint things which are used in the core itself; the file you modified is not included there. You should see the lint warnings when you compile the simple system for Verilator.

**Comment by towoe** [comment]
> That will only lint things which are used in the core itself; the file you modified is not included there. You should see the lint warnings when you compile the simple system for Verilator.

Thanks for explaining that. No warnings are produced for `sim_finish`. Could be the comparison which makes Verilator assume that the width is necessary.

**Comment by imphil** [comment]
Thanks for checking!

**Pull request merged**
