### PR TITLE
[lint] Remove whitespace from existing source files

### PR DESCRIPTION
**Pull request by marnovandermaas**

### CODE REVIEW

**Comment by marnovandermaas** [comment]
@hcallahan-lowrisc told me that it is not desirable to change code in the `vendor` directory, especially for something trivial like whitespace. I should change this pull request to only make whitespace corrections to files that are not vendored in.

**Comment by hcallahan-lowrisc** [comment]
For things like whitespace, if you feel strongly there is always the patching mechanism (see ibex/vendor/google_riscv-dv.vendor.hjson and /ibex/vendor/patches/google_riscv-dv/)

**Comment by marnovandermaas** [comment]
Ok, I have now changed this pull request to only remove the trailing white-space from the source code that is not vendored in.

**Review by hcallahan-lowrisc — APPROVED** [review]
Thanks for the cleanup, always welcome! It would be great to setup some more linting / pre-commit checks for this stuff at some point.

**Comment by marnovandermaas** [comment]
> Thanks for the cleanup, always welcome! It would be great to setup some more linting / pre-commit checks for this stuff at some point.

Yes, agreed. I'll have a look at that when I have time.

**Pull request merged**
