### PR TITLE
Make --seed argument more helpful in core_ibex/sim.py

### PR DESCRIPTION
**Pull request by rswarbrick**
Now, successive test iterations use successive seeds. So if you pass
`--seed 123` and run ten iterations, they will run with seeds 123, 124,
... through 133.

### CODE REVIEW

**Comment by udinator** [comment]
Adding @taoliug to take a look at this PR, since it pretty closely relates to google/riscv-dv#570

**Comment by udinator** [comment]
I think Tao mentioned this in the riscv-dv PR, but I alos think it's better to randomize the seeds instead of fixing them at top level (and incrementing by 1 for every iteration) - could you implement something similar to how riscv-dv creates a `seed.yaml` file to allow rerunning full regressions?
This would allow full randomization of the seeds used to not limit the size of the explored state space while also allowing regressions to be rerun.

**Comment by rswarbrick** [comment]
@udinator I don't think I understand this comment. Assuming you have a half-decent PRNG, reading 100 seeds from a `seed.yaml` has the same "randomness" as picking a starting seed and running 100 seeds starting from there. The latter option means I can specify my regression run with a single number. The former requires me to generate (and check in) a YAML file.

As I assume you understand, whether I specify seeds or not is basically the difference between soak testing and regression testing. Clearly, we need to support both, and we do (don't specify a seed for soak testing; generate a YAML file for regression testing).

However, our tools currently do something silly if you ask for a seed and more than one test (which is what your issue #859 reports). We should either throw an error ("Hey, this doesn't make sense. Please write a list of numbers in a file for me.") or, better, do something sensible. That's what these patches do.

**Comment by rswarbrick** [comment]
Right. I've put the new behaviour in a differently named argument and this PR now contains the vendor patch that pulls in the new riscv-dv code.

**Pull request merged**
