### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by dawidzim**
Hey!
I update path to vmem file in Riviera-PRO readme.

### CODE REVIEW

**Comment by dawidzim** [comment]
yeah, but FuseSoC moving us to sim folder, so we need to pass path like we are in `build/lowrisc...simple_system/sim/`

**Comment by rswarbrick** [comment]
I think I don't understand, sorry. Calling `fusesoc` doesn't change the current working directory of your shell and the `.vmem` file appears where the readme says. For example, I just ran the following:

```
$ git clean -fxd
$ make -C examples/sw/simple_system/hello_test
make: Entering directory '/src/lr/ibex/examples/sw/simple_system/hello_test'
riscv32-unknown-elf-gcc -march=rv32imc -mabi=ilp32 -static -mcmodel=medany -Wall -g -Os -fvisibility=hidden -nostdlib -nostartfiles -ffreestanding  -MMD -c -I/src/lr/ibex/examples/sw/simple_system/common -o /src/lr/ibex/examples/sw/simple_system/common/simple_system_common.o /src/lr/ibex/examples/sw/simple_system/common/simple_system_common.c
riscv32-unknown-elf-gcc -march=rv32imc -mabi=ilp32 -static -mcmodel=medany -Wall -g -Os -fvisibility=hidden -nostdlib -nostartfiles -ffreestanding  -MMD -c -I/src/lr/ibex/examples/sw/simple_system/common -o hello_test.o hello_test.c
riscv32-unknown-elf-gcc -march=rv32imc -mabi=ilp32 -static -mcmodel=medany -Wall -g -Os -fvisibility=hidden -nostdlib -nostartfiles -ffreestanding  -MMD -c -I/src/lr/ibex/examples/sw/simple_system/common -o /src/lr/ibex/examples/sw/simple_system/common/crt0.o /src/lr/ibex/examples/sw/simple_system/common/crt0.S
riscv32-unknown-elf-gcc -march=rv32imc -mabi=ilp32 -static -mcmodel=medany -Wall -g -Os -fvisibility=hidden -nostdlib -nostartfiles -ffreestanding  -T /src/lr/ibex/examples/sw/simple_system/common/link.ld /src/lr/ibex/examples/sw/simple_system/common/simple_system_common.o hello_test.o  /src/lr/ibex/examples/sw/simple_system/common/crt0.o -o hello_test.elf 
riscv32-unknown-elf-objcopy -O binary hello_test.elf hello_test.bin
srec_cat hello_test.bin -binary -offset 0x0000 -byte-swap 4 -o hello_test.vmem -vmem
riscv32-unknown-elf-objdump -fhSD hello_test.elf > hello_test.dis
make: Leaving directory '/src/lr/ibex/examples/sw/simple_system/hello_test'
$ ls examples/sw/simple_system/hello_test/*.vmem
examples/sw/simple_system/hello_test/hello_test.vmem
```

**Comment by tomroberts-lowrisc** [comment]
That parameter ends up being passed into the ram model which runs:
`$readmemh(MemInitFile, mem);`
I guess the path to MemInitFile for that call is relative to the simulator's run location?

**Comment by rswarbrick** [comment]
Oh, I see. That's upsetting - it seems that VCS doesn't change directory in the same way. Probably best to change the example to something like:

```
fusesoc --cores-root=. run --target=sim --tool=rivierapro lowrisc:ibex:ibex_simple_system --RV32M=1 --RV32E=0 --SRAMInitFile=$(readlink -f <sw_vmem_file>)
```

which means you don't have to embed a magic `../../../../how/many/do/i/need/../` in your README.

**Comment by dawidzim** [comment]
@rswarbrick I updated readme as you suggest

**Comment by rswarbrick** [comment]
I'm really sorry, but I meant to update the example command. I think that will be much easier to copy/paste and also makes a bit more sense: rather than saying "the file at <shell-command>", you say "use the file at <path> with <shell-command>".

**Comment by dawidzim** [comment]
Sorry my bad, now should be ok

**Pull request merged**
