### PR TITLE
[rtl/dv] Add assertions for icache scramble keys

### PR DESCRIPTION
**Pull request by andreaskurth**
This commit adds two assertions in `ibex_top` to ensure that the scramble key is correctly applied to the icache scrambled memory primitives.  Those assertions previously existed in the module that instantiated Ibex in OpenTitan, but the reference into the generate loops was problematic for some EDA tools; see lowRISC/opentitan#17155.

### CODE REVIEW

**Review by vogelpi — APPROVED** [review]
Thanks @andreaskurth for taking care of this, the changes LGTM but the smoketest for the opentitan config which uses these changes is currently failing with Xcelium. This needs to be debugged first.

**Comment by andreaskurth** [comment]
Thanks @vogelpi. I had a quick look, and for 3 out of 4 programs that are part of the smoke test, the assertion fails. Those failures did not occur in the OT tests, but Ibex is operated in more corner conditions in this DV environment. If changing the assertions to `[0:$]`, they don't fail -- but maybe a reset at the end of the test kills the assertions? I plan to debug this with waves as soon as I can allocate some time for that.

**Comment by andreaskurth** [comment]
I found the problem: The assertions previously used the input scramble key (`scramble_key_i`) even though they tolerated a delay after which the input scramble key was not necessarily valid anymore (i.e., `scramble_key_valid_i` could go low and `scramble_key_i` could take any value).  This mistake has been corrected by sampling the input scramble key for the assertions when it is valid and using the sampled value in the comparison of the assertions.

**Comment by vogelpi** [comment]
Thanks for debugging and fixing this @andreaskurth . It makes sense and your changes LGTM.

**Review by GregAC — APPROVED** [review]

**Pull request merged**
