### PR TITLE
Update google_riscv-dv to google/riscv-dv@473dc68

### PR DESCRIPTION
**Pull request by udinator**
Update code from upstream repository https://github.com/google/riscv-
dv to revision 473dc68630e2210f48fe9ea4352c6e9659db5656

* Sphinx: Add generating pdf file (google/riscv-dv#431) (Hai Hoang
  Dang)
* integrate directed asm_tests with yaml flow (Udi Jonnalagadda)
* Fix running cov without arguments (google/riscv-dv#433) (Hai Hoang
  Dang)
* Add setup Travis CI for tracking build docs, and install
  (google/riscv-dv#430) (Hai Hoang Dang)
* Add handling KeyboardInterrupt for run_cmd and run_parallel_cmd
  (google/riscv-dv#424) (Hai Hoang Dang)
* Sphinx: add basic page for structure of the document (google/riscv-
  dv#428) (Hai Hoang Dang)
* README.md: Update the information relating to usage (google/riscv-
  dv#426) (Hai Hoang Dang)
* Add initial Sphinx docs (google/riscv-dv#427) (Hai Hoang Dang)
* Fix typo in the testlist (google/riscv-dv#423) (taoliug)
* Add try-except for handling KeyboardInterrupt (google/riscv-dv#421)
  (Hai Hoang Dang)
* Update information about instruction for running scripts
  (google/riscv-dv#420) (Hai Hoang Dang)
* Add vector permutation, reduction, mask instructions (google/riscv-
  dv#422) (taoliug)
* Python package (google/riscv-dv#419) (Hai Hoang Dang)
* Refactor the code for cov.py (google/riscv-dv#416) (Hai Hoang Dang)
* Update ovpsim config for vector extesion (google/riscv-dv#415)
  (taoliug)
* Fix coverage flow issue (google/riscv-dv#414) (taoliug)
* Add missing license header (google/riscv-dv#412) (taoliug)
* Fix typo in cov_test (google/riscv-dv#410) (taoliug)
* Add vector floating point instructions (google/riscv-dv#409)
  (taoliug)
* Add fixed point arithmetic vector instruction (google/riscv-dv#408)
  (taoliug)
* cov.py: Generate error when it cannot find spike_sim directory
  (google/riscv-dv#407) (Hai Hoang Dang)
* Add vector CSR initialization routine (google/riscv-dv#405)
  (taoliug)
* Create vector extension target, add basic enums (google/riscv-
  dv#404) (taoliug)
* Fix qrun sim warning (google/riscv-dv#402) (taoliug)
* Try fix qrun constraint solver issue (google/riscv-dv#401) (taoliug)
* Fix simulation warning (google/riscv-dv#400) (taoliug)
* run.py: Generate error for gcc compile when it cannot find assembly
  files (google/riscv-dv#398) (Hai Hoang Dang)
* Add numeric corner case test, misc coverage fixes (google/riscv-
  dv#396) (taoliug)
* Switch to new CSV format (google/riscv-dv#395) (taoliug)
* misc fixes for the coverage model (google/riscv-dv#394) (taoliug)
* Fix new CSV coverage flow issue (google/riscv-dv#392) (taoliug)
* Integrate new trace CSV format with coverage flow (google/riscv-
  dv#390) (taoliug)
* Add experimental script for the new CSV format (google/riscv-dv#389)
  (taoliug)
* Support flexible running directed assembly tests (google/riscv-
  dv#386) (Hai Hoang Dang)
* run.py: Enhance passing argument for gen function (google/riscv-
  dv#382) (Hai Hoang Dang)
* Fix qrun issue, take 2 (google/riscv-dv#384) (taoliug)
* Attempt to fix qrun issue (google/riscv-dv#383) (taoliug)
* Fix (google/riscv-dv#381) (taoliug)
* Fix typo (google/riscv-dv#380) (taoliug)
* Fix qrun simulation issue (google/riscv-dv#379) (taoliug)
* Cleaning the output directory by default. Using exist output
  directory (google/riscv-dv#377) (Hai Hoang Dang)
* Fix ius compilation error temporarily (google/riscv-dv#378)
  (taoliug)
* Functional coverage improvement (google/riscv-dv#376) (taoliug)
* Add unaligned jump instruction support (google/riscv-dv#375)
  (taoliug)
* move handcoded asm_test generation into separate output directory
  (Udi Jonnalagadda)
* Ignore return code for ovpsim sim (google/riscv-dv#371) (taoliug)
* Fix mie compare mismatch (google/riscv-dv#370) (taoliug)
* Fix directory/file name for assembly test flow (google/riscv-dv#369)
  (taoliug)
* Fix error in README (google/riscv-dv#368) (taoliug)
* Add sample rv32imc test (google/riscv-dv#367) (taoliug)
* Fix typo (google/riscv-dv#366) (taoliug)
* Support running regression with hand-coded assembly tests
  (google/riscv-dv#365) (taoliug)

Signed-off-by: Udi <udij@google.com>

### CODE REVIEW

**Comment by taoliug** [comment]
This is a lot of changes, please make sure you have a PR for the required changes for ibex DV environment before vendor in the upstream changes.

**Comment by imphil** [comment]
Please avoid adding generated documents, especially generated binaries. There's no need to add the PDF to the tree, users can build it themselves (or you use readthedocs or similar services to auto-generate the PDF on the fly).

**Comment by udinator** [comment]
Closing this PR for now, will re-open a new vendor PR later, filtering out documentation and including integration changes to get these changes to work with Ibex.

**Comment by imphil** [comment]
I don't mind the documentation being vendored in as well. It's of course up to the upstream riscv-dv project, but I'd just go ahead and remove the PDF there and then vendor the whole tree in, as we are doing currently.

**Pull request closed without merging**
