### PR TITLE
[icache, dv] Added scrambling agent to verify scrambling in RAMs

### PR DESCRIPTION
**Pull request by prajwalaputtappa**
This commit adds a new scrambling agent to drive scrambling key and valid to the data and tag memory interfaces.

### CODE REVIEW

**Comment by rswarbrick** [comment]
This looks fine, except for the vendoring part, where I think you copied the files across manually? The right thing to do is to update `lowrisc_ip.vendor.hjson` and then re-run the vendoring tool to grab the files.

**Comment by prajwalaputtappa** [comment]
> This looks fine, except for the vendoring part, where I think you copied the files across manually? The right thing to do is to update `lowrisc_ip.vendor.hjson` and then re-run the vendoring tool to grab the files.

I've generated the push pull agent using the script.

**Comment by rswarbrick** [comment]
Ah, could you re-do this so that you run the vendoring script first? At the moment, I think the first commit has the manually copied files, which get overwritten by the vendoring commit: it should probably go the other way around.

**Review by rswarbrick — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
