### PR TITLE
Switch from 'bool' to 'int' parameters in fusesoc core files

### PR DESCRIPTION
**Pull request by rswarbrick**
Fusesoc has an unfortunate bug[1] where a boolean parameter which has
default true can't be disabled. For now, just make all our boolean
parameters back into integers again. In the future, when that's fixed,
maybe we should switch things back.

[1] https://github.com/olofk/fusesoc/issues/392

### CODE REVIEW

**Comment by GregAC** [comment]
I also note that whilst CI is passing the ibex_config.py is failing for some reason (though of course works fine when it's run standalone as the first step...). I should look into what's happening.

**Comment by rswarbrick** [comment]
@GregAC Is this as simple as changing the True/False constants in `ibex_configs.yaml` to 1/0, or is there something cleverer I need to do?

**Comment by GregAC** [comment]
just switch them to 0/1

**Comment by GregAC** [comment]
Could also remove support for boolean parameters altogether from ibex_config.py but I think it's fine to just avoid using them for now.

**Comment by rswarbrick** [comment]
@GregAC Done!

**Comment by rswarbrick** [comment]
> Could also remove support for boolean parameters altogether from ibex_config.py but I think it's fine to just avoid using them for now.

I agree, let's leave them in. Eventually, we'll hopefully be able to use bools again with fusesoc.

**Comment by rswarbrick** [comment]
Cool. If I forget, feel free to rebase it yourself or ping me a reminder!

**Pull request merged**
