### PR TITLE
Changes simulation command for Riviera 2021.04

### PR DESCRIPTION
**Pull request by dawidzim**
Hey!
Few changes in Riviera-PRO compilation and simulation command

### CODE REVIEW

**Comment by rswarbrick** [comment]
Please can you explain why these changes are needed? Was the previous command wrong? Or is it to match a newer version of Riviera? Or something else?

**Comment by dawidzim** [comment]
I am making these changes to be compatible with the new Riviera-PRO version

**Comment by rswarbrick** [comment]
Ok. Do the new command lines also work for older versions of Riviera? Can we update some documentation to explain what this works with?

**Comment by rswarbrick** [comment]
Well, we can't merge this commit at the moment because we, the maintainers, don't understand what's going on. Please could you explain how these command line changes relate to different Riviera versions? In particular, if someone has an older version that worked with the existing code, will this change break things for them?

**Comment by dawidzim** [comment]
At this point verification of Ibex works only  with version 2021.04. Older version have limitations and code will compile with errors.

The command which I added has worked since version 2020.04

**Comment by rswarbrick** [comment]
Ok, great. Please could you update the commit message with that information (so that people looking through the history in the future know what's going on)? Then we can merge this.

**Comment by dawidzim** [comment]
@rswarbrick Is it ok now?

**Comment by rswarbrick** [comment]
I mean: please force-push to update the commit message in the git commit.

**Comment by rswarbrick** [comment]
Thanks for the update. I've just force-pushed something more like what I meant (with a standard git commit message format, plus a long-form explanation that will make sense to a future reader). Let me know if you don't want this going in. Otherwise, I'll merge once this passes CI.

**Comment by dawidzim** [comment]
That looks great :) Thanks!

**Review by rswarbrick — APPROVED** [review]

**Comment by rswarbrick** [comment]
Actually, no point in waiting for CI: we don't do anything that uses this bit of the file. Merging now!

**Pull request merged**
