### PR TITLE
[dv] Improve objdump and prettify scripts

### PR DESCRIPTION
**Pull request by marnovandermaas**
- Shellcheck objdump script
- Check for RISCV_TOOLCHAIN variable
- Shellcheck prettify script

### CODE REVIEW

**Review by hcallahan-lowrisc — COMMENTED** [review]
Our docs [currently say](https://github.com/lowRISC/ibex/blame/master/doc/03_reference/verification.rst#L125) that you need to have set the RISCV_TOOLCHAIN environment variable, could we just leave that to be the only working option? I feel like having two options is a little confusing. WDYT?

**Comment by hcallahan-lowrisc** [comment]
The shellcheck improvements are very welcome. Thanks.

**Comment by hcallahan-lowrisc** [comment]
Riscv-dv picks up gcc and objcopy from the environment variables [RISCV_GCC](https://github.com/google/riscv-dv/blob/c6acc1897429f5245cc89b2ecee2e3eefdefd18d/run.py#L432) and RISCV_OBJCOPY. Currently our docs say to define those relative to the RISCV_TOOLCHAIN envvar. 
I think for now it would be preferable to have a single-source-of-truth for how to setup the ibex build system. Adding to the PATH works too but I can imagine a situation where one accidentally ends up with two riscv toolchains accessible to the shell and subtle chaos ensues. I think having a single method supported for now makes sense in the short term.

**Comment by marnovandermaas** [comment]
Ok, that makes sense and thanks for the explanation. I have changed it to just throw an error if `RISCV_TOOLCHAIN` does not exist.

**Review by hcallahan-lowrisc — APPROVED** [review]

**Pull request merged**
