### PR TITLE
[syn] Fix path in synthesis script

### PR DESCRIPTION
**Pull request by tomroberts-lowrisc**
Path to primitives has been updated

Signed-off-by: Tom Roberts <tomroberts@lowrisc.org>

### CODE REVIEW

**Review by rswarbrick — APPROVED** [review]
Oh, sorry, this was my fault. Thanks!

**Comment by tomroberts-lowrisc** [comment]
Seems all PRs are failing CI at the moment
```
Collecting rst2pdf
  Downloading rst2pdf-0.93.tar.gz (1.3 MB)
ERROR: Requested rst2pdf from ...
```
@imphil is this a known issue?

**Comment by imphil** [comment]
@tomroberts-lowrisc I'm looking now (rst2pdf is a dependency of riscv-dv, which is actually not used in our setup)

**Comment by imphil** [comment]
@tomroberts-lowrisc "solution" is in https://github.com/lowRISC/ibex/pull/1208

**Pull request merged**
