### PR TITLE
[ci] Consolidate Verible linting workflow into one stage

### PR DESCRIPTION
**Pull request by jwnrt**
Demo PR on my local fork: https://github.com/jwnrt/ibex/pull/1

## Problem

The current GitHub Actions (for Verible linting) have some dependencies on actions that use Node.js v12 (`actions/checkout@v2` and `actions/github-script@v3.1.0`) which [will be dropped on 2023-08-14](https://github.blog/changelog/2023-07-17-github-actions-removal-of-node12-from-the-actions-runner/).

These deprecated actions have newer versions that use Node.js 16, but `github-script` is a non-trivial update since our usage includes some actual Node.js code that needs porting.

## Suggested fix

The docs for the Verible linter action [have been updated](https://github.com/chipsalliance/verible-linter-action/pull/31) to suggest using a single workflow, avoiding the need for `github-script`.

This PR updates to using this workflow, allowing us to update from deprecated dependencies.

We've been using this consolidated version of the linting workflow in [lowRISC/opentitan](https://github.com/lowRISC/opentitan/pull/18910) for a couple of weeks ([example](https://github.com/lowRISC/opentitan/pull/19207)). I believe the only issues we've seen were from an unrelated curl breakage.

### CODE REVIEW

**Review by marnovandermaas — COMMENTED** [review]
Thanks for making these changes. How can we test this? I want to make sure that the linting keeps running without unintentionally breaking it.

**Comment by jwnrt** [comment]
It’s difficult to test here but the way we did it on OpenTitan was:

1. Merge the PR to my fork of the repo.
2. Have somebody open a PR on my fork with an intentional mistake.
3. Ensure the review comments are added.

I can sort this out next week.

**Comment by jwnrt** [comment]
@marnovandermaas here's a PR on my local fork showing this action running: https://github.com/jwnrt/ibex/pull/1

**Review by marnovandermaas — APPROVED** [review]
Ok, looks good to me, thanks for performing the test.

**Comment by jwnrt** [comment]
Looks like the merge queue failure is due to the Azure pipeline not being able to checkout the merged commit.
I'll try work out what's going on.

**Comment by jwnrt** [comment]
Rebased and tried again and it worked! Not sure what the actual issue was...

**Pull request merged**
